routes/admin.php
<?php

use App\Http\Controllers\TinymceController;
use App\Http\Controllers\Backend\{Auth\LoginController,
    CategoryController,
    ConfigController,
    MainInfoController,
    PageController,
    PhotoController,
    PostController,
    Settings\LogController,
    Settings\SettingController,
    SiteController,
    TagController,
    TranslateController,
    UserController};
use App\Http\Controllers\CkeditorController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth', 'preventBackHistory'])->group(function () {
    Route::get('/', [SiteController::class, 'index'])->name('home');
    Route::get('/change-locale/{lang}', [SiteController::class, 'changeLocale'])->name('change-locale');

    Route::middleware('can:settings/*')->group(function () {
        Route::resource('settings', SettingController::class)->except(['show']);
        Route::resource('logs', LogController::class)->only(['index', 'show']);
        Route::put('settings/chosen-tags/update/{id}', [SettingController::class, 'updateChosenTags'])->name('settings.chosen-tags.update');
    });

    Route::middleware('can:categories/*')->group(function () {
        Route::resource('categories', CategoryController::class)->except(['show']);
        Route::get('categories/move/{id}/{type}', [CategoryController::class, 'move'])
            ->where('type', 'up|down')
            ->where('id', '[0-9]+')
            ->name('categories.move');
        Route::get('categories/translate-list', [CategoryController::class, 'translateList'])
            ->middleware('crossAjax')
            ->name('categories.translate-list');
        Route::get('categories/create-translate', [CategoryController::class, 'create'])
            ->middleware('crossAjax')
            ->name('categories.createTranslate');
    });

    Route::middleware('can:tags/*')->group(function () {
        Route::get('tags/merge', [TagController::class, 'merge'])
            ->name('tags.merge');
        Route::resource('tags', TagController::class);
    });

    Route::get('post/restore/{id}', [PostController::class, 'restore'])
        ->middleware('can_any:post/*|post/restore')
        ->name('post.restore');
    Route::get('post/publish/{id}', [PostController::class, 'publish'])
        ->middleware('can_any:post/*|post/publish')
        ->name('post.publish');
    Route::get('post/reject/{id}', [PostController::class, 'reject'])
        ->middleware('can_any:post/*|post/reject')
        ->name('post.reject');

    Route::get('post/delete-reason', [PostController::class, 'deleteReason'])
        ->middleware('can_any:*/delete|posts/*')
        ->name('post.deleteReason');

    Route::resource('post', PostController::class);
    Route::put('post/update-counts/{id}', [PostController::class, 'updateCounts'])
        ->middleware('can_any:post/*|posts/*')
        ->name('post.update-counts');
    Route::get('post/cancel-form/{id}', [PostController::class, 'cancelForm'])
        ->name('post.cancel-form');

    Route::get('posts/tag-list', [PostController::class, 'tagList'])
        ->middleware(['can_any:posts/*|posts/create|posts/edit', 'crossAjax'])
        ->name('posts.tag-list');

    Route::get('posts/translate-list', [PostController::class, 'translateList'])
        ->middleware('can_any:posts/*|posts/create|posts/edit')
        ->name('posts.translate-list');

    Route::get('posts/reference-list', [PostController::class, 'referenceList'])
        ->middleware(['can_any:posts/*|posts/create|posts/edit', 'crossAjax'])
        ->name('posts.reference-list');

    Route::get('posts/create-translate', [PostController::class, 'create'])
        ->middleware(['can_any:posts/*|posts/create', 'crossAjax'])
        ->name('posts.createTranslate');

    Route::get('posts/{type}', [PostController::class, 'index'])
        ->middleware('post_authorize')
        ->name('posts.list');

    Route::middleware('can:pages/*')->group(function () {
        Route::resource('pages', PageController::class)->except(['show']);
        Route::post('pages/image-delete/{id}', [PageController::class, 'imageDelete'])
            ->where('id', '[0-9]+')
            ->name('pages.image-delete');
        Route::get('pages/move/{id}/{type}', [PageController::class, 'move'])
            ->where('type', 'up|down')
            ->where('id', '[0-9]+')
            ->name('pages.move');
    });

    Route::middleware('can:users/*')->group(function () {
        Route::resource('users', UserController::class);
        Route::post('users/delete-thumb/{id}', [UserController::class, 'deleteThumb'])
            ->name('users.delete-image');
    });

    Route::middleware('can:main-info/*')->group(function () {
        Route::post('main-info/delete-logo/{id}/{lang}', [MainInfoController::class, 'deleteLogo'])
            ->name('main-info.delete-logo');
        Route::post('main-info/delete-favicon/{id}/{lang}', [MainInfoController::class, 'deleteFavicon'])
            ->name('main-info.delete-favicon');
        Route::get('main-info', [MainInfoController::class, 'index'])->name('main-info');
        Route::put('main-info', [MainInfoController::class, 'update'])->name('main-info.update');
    });

    Route::resource('configs', ConfigController::class)
        ->middleware('can:configs/*')
        ->except(['show']);

    Route::resource('translations', TranslateController::class)
        ->middleware('can:translations/*')
        ->except(['show']);

    Route::resource('translates', TranslateController::class)
        ->middleware('can:translations/*')
        ->except(['show']);

    Route::get('translates/view', [TranslateController::class, 'view'])
        ->middleware('can:translations/*')
        ->name('translates.view');

    Route::post('ckeditor/image_upload', [CkeditorController::class, 'upload'])->name('ckeupload');
    Route::post('tinymce/addWidget', [TinymceController::class, 'addWidget'])
        ->name('tinymce.addWidget');

    Route::prefix('photos')->middleware('can:photos/*')->name('photos.')->group(function () {
        Route::get('index', [PhotoController::class, 'index'])->name('index');
        Route::get('folder', [PhotoController::class, 'folderIndex'])->name('folder');
        Route::get('trash', [PhotoController::class, 'trashIndex'])->name('trash');
        Route::get('restore', [PhotoController::class, 'restore'])->name('restore');
        Route::post('create', [PhotoController::class, 'create'])->name('create');
        Route::get('update', [PhotoController::class, 'update'])->name('update');
        Route::post('update', [PhotoController::class, 'update'])->name('update.submit');
        Route::post('size', [PhotoController::class, 'size'])->name('size.submit');
        Route::get('create-folder', [PhotoController::class, 'folderCreate'])->name('create-folder');
        Route::get('delete-folder', [PhotoController::class, 'folderDelete'])->name('delete-folder');
        Route::get('update-folder', [PhotoController::class, 'folderUpdate'])->name('update-folder');
        Route::post('update-folder', [PhotoController::class, 'folderUpdate'])->name('update-folder.submit');
        Route::post('create-folder', [PhotoController::class, 'folderCreate'])->name('create-folder.submit');
        Route::post('delete', [PhotoController::class, 'delete'])->name('delete');
        Route::post('soft-delete', [PhotoController::class, 'softDelete'])->name('softDelete');
        Route::post('crop', [PhotoController::class, 'crop'])->name('crop');
        Route::get('sort', [PhotoController::class, 'sort'])->name('sort');
        Route::post('render-gallery', [PhotoController::class, 'renderGallery'])->name('render-gallery');
        Route::post('get-size', [PhotoController::class, 'getSize'])->name('get-size');
    });
});

Route::middleware(['preventBackHistory'])->group(function () {
    Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('login', [LoginController::class, 'login'])->name('login.login');
    Route::get('logout', [LoginController::class, 'logout'])->name('logout');
});

routes/web.php
<?php

//

app/Models/User.php
<?php

namespace App\Models;

use App\Models\Post\Post;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $fillable = ['visited_at'];

    const DEFAULT_THUMB = 'user.png';

    public function getFullNameAttribute()
    {
        return "{$this->name}";
    }

    public static function create($name, $email, $status, $password)
    {

        $model = new static();

        $model->name = $name;
        $model->email = $email;
        $model->status = $status;
        $model->password = Hash::make($password);

        return $model;
    }

    public function edit($name, $email, $password)
    {
        $this->name = $name;
        $this->email = $email;

        if ($password) {
            $this->password = Hash::make($password);
        }
    }

    public function attachThumb($thumb)
    {
        $this->thumb = $thumb;
    }

    public function detachThumb()
    {
        $this->thumb = null;
    }

    public function isAdmin() {
        return $this->roles()->where('name', 'admin')->exists();
    }

    public function posts()
    {
        return $this->hasMany(Post::class,'user_id')
            ->orderByDesc('published_at');
    }

    public function getRole()
    {
        return $this->roles()->first();
    }
}

app/Http/Controllers/Backend/BaseController.php
<?php

namespace App\Http\Controllers\Backend;

class BaseController
{
}

app/Http/Controllers/Backend/CategoryController.php
<?php
declare(strict_types=1);

namespace App\Http\Controllers\Backend;

use DB;
use Exception;
use RuntimeException;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Repositories\CategoryRepository;
use App\Http\Controllers\Controller;
use Illuminate\Http\RedirectResponse;
use App\Services\manager\CategoryService;
use Itstructure\GridView\DataProviders\EloquentDataProvider;
use App\Http\Requests\Category\{CategoryCreateRequest, CategoryUpdateRequest};

class CategoryController extends Controller
{

    public function __construct(
        private CategoryRepository $categoryRepository,
        private CategoryService $categoryService
    )
    {
    }

    public function index()
    {
        $lang = request()->input('filters.language');
        if ($lang) {
            session()->put('current-lang', $lang);
        }
        $lang  = (session()->get('current-lang') ?? $lang) ?? config('app.admin_content_locale');
        $query = Category::query()
            ->where('language', $lang)
            ->defaultOrder();

        $dataProvider = new EloquentDataProvider($query);

        return view('backend.categories.index', [
            'dataProvider' => $dataProvider
        ]);
    }

    public function create()
    {
        if ($lang = request()->get('lang')) {
            if ($id = request()->get('id')) {
                $category = Category::findOrFail($id);
                if ($translatedCategory = Category::where('group_id', $category->group_id)->where('language', $lang)->first()) {
                    return redirect()->route('admin.categories.edit', $translatedCategory);
                }
            }

            return view('backend.categories.create', [
                'lang'                 => $lang,
                'translatedCategoryId' => request('id'),
            ]);
        }

        return redirect()->route('admin.categories.index');
    }

    public function store(CategoryCreateRequest $request)
    {
        try {
            $this->categoryService->create($request);
            return redirect()->route('admin.categories.index')
                ->with('success', trans('form.success.save'));
        } catch (Exception $e) {
            return redirect()->route('admin.categories.index')
                ->with('error', trans('form.error.save'));
        }
    }

    public function show(Category $category)
    {
        return view('backend.categories.view', [
            'category' => $category
        ]);
    }

    public function edit(Category $category)
    {
        return view('backend.categories.update', [
            'category'             => $category,
            'translatedCategories' => $this->categoryRepository->translatedCats($category->group_id, $category->id),
        ]);
    }

    public function update(CategoryUpdateRequest $request, Category $category)
    {
        try {
            $this->categoryService->update($request, $category);
            return redirect()->route('admin.categories.index')
                ->with('success', trans('form.success.save'));
        } catch (Exception $e) {
            return redirect()->route('admin.categories.index')
                ->with('error', trans('form.error.save'));
        }
    }

    public function destroy(Category $category): RedirectResponse
    {
        try {
            $this->categoryService->remove($category);
            return redirect()->route('admin.categories.index')
                ->with('success', trans('form.success.delete'));
        } catch (RuntimeException $e) {
            return redirect()->route('admin.categories.index')
                ->with('error', trans('form.error.delete'));
        }
    }

    public function move(int $id, string $type): RedirectResponse
    {
        try {
            /** @var Category $category */
            $category = Category::findOrFail($id);
            ($type == 'up') ? $category->up() : $category->down();
        } catch (Exception $e) {
            \Log::debug($e);
        }

        return redirect()->route('admin.categories.index', ['page' => \request('page'), '_debug_' => true]);
    }

    public function translateList(Request $request)
    {
        $posts = $this->categoryRepository->getByQuery($request->q, $request->lang, $request->chosen)->toArray();

        return response()->json(['results' => array_values($posts)]);
    }

}

app/Http/Controllers/Backend/CityController.php
<?php
declare(strict_types=1);

namespace App\Http\Controllers\Backend;

use App\Helpers\NodeHelper;
use App\Http\Controllers\Controller;
use App\Http\Requests\City\CityCreateRequest;
use App\Http\Requests\City\CityUpdateRequest;
use App\Models\City\City;
use App\Services\manager\CityService;
use Exception;
use Illuminate\Http\RedirectResponse;
use Itstructure\GridView\DataProviders\EloquentDataProvider;
use RuntimeException;

class CityController extends Controller
{
    private $cityService;

    public function __construct(CityService $cityService)
    {
        $this->cityService = $cityService;
    }

    public function index()
    {
        $query = City::query()->withDepth()->defaultOrder();
        $dataProvider = new EloquentDataProvider($query);

        return view('backend.cities.index', [
            'dataProvider' => $dataProvider
        ]);
    }

    public function create()
    {
        $parents = (new NodeHelper(City::class))->map();

        return view('backend.cities.create', compact('parents'));
    }

    public function store(CityCreateRequest $request)
    {
        try {
            $this->cityService->create($request);
            return redirect()->route('admin.cities.index')
                ->with('success', trans('form.success.save'));
        } catch (Exception $e) {
            return redirect()->route('admin.cities.index')
                ->with('error', trans('form.error.save'));
        }
    }

    public function show(City $category)
    {
        return view('backend.cities.view', [
            'category' => $category
        ]);
    }

    public function edit(City $city)
    {
        $parents = (new NodeHelper($city))->map();

        return view('backend.cities.update', compact('city', 'parents'));
    }

    public function update(CityUpdateRequest $request, City $city)
    {
        try {
            $this->cityService->update($request, $city);
            return redirect()->route('admin.cities.index')
                ->with('success', trans('form.success.save'));
        } catch (Exception $e) {
            return redirect()->route('admin.cities.index')
                ->with('error', trans('form.error.save'));
        }
    }

    public function destroy(City $city): RedirectResponse
    {
        try {
            $this->cityService->remove($city);
            return redirect()->route('admin.cities.index');
        } catch (RuntimeException $e) {
            return redirect()->route('admin.cities.index')->with('error', $e->getMessage());
        }
    }

    public function move(int $id, string $type): RedirectResponse
    {
        $category = City::findOrFail($id);
        ($type == 'up') ? $category->up() : $category->down();

        return redirect()->back();
    }
}

app/Http/Controllers/Backend/Settings/LogController.php
<?php

namespace App\Http\Controllers\Backend\Settings;

use App\Models\Audit;
use App\Http\Controllers\Controller;
use Itstructure\GridView\DataProviders\EloquentDataProvider;

class LogController extends Controller
{
    public function index()
    {
        $dataProvider = new EloquentDataProvider(Audit::query());
        return view('backend.logs.index', [
            'dataProvider' => $dataProvider
        ]);
    }
}

resources/views/backend/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title') | Admin Panel</title>
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    @include('backend.layouts.styles')
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">

        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="{{ route('admin.home') }}" class="nav-link">@lang('admin.home_page')</a>
            </li>
        </ul>

        <ul class="navbar-nav ml-auto">

            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    {{ strtoupper(app()->getLocale()) }}
                </a>
                <div class="dropdown-menu dropdown-menu-sm-right">
                    @foreach(config('app.admin_locales') as $locale)
                        @if($locale != app()->getLocale())
                            <a href="{{ route('admin.change-locale', $locale) }}" class="dropdown-item">{{ strtoupper($locale) }}</a>
                        @endif
                    @endforeach
                </div>
            </li>
            <li class="nav-item dropdown profile-button">
                <a class="nav-link" data-toggle="dropdown" href="javascript:void(0);" aria-expanded="false">
                    <img src="{{ user_image(auth()->user()?->thumb) }}" class="img-circle elevation-2" alt="User Image" style="height: 25px; margin-right: 5px;">
                </a>
                <div class="dropdown-menu dropdown-menu-right" style="left: inherit; right: 0px;">
                    <a href="{{ route('admin.users.show', auth()->id()) }}" class="dropdown-item"> {{ auth()->user()->full_name }}</a>
                    <div class="dropdown-divider"></div>
                    <a data-action="{{ route('admin.logout') }}" href="javascript:void(0);" class="dropdown-item confirm-btn" data-confirm="{{ trans('admin.logout_confirm') }}">{{ trans('admin.logout') }} <i class="fa fa-sign-out-alt"></i></a>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link" data-widget="fullscreen" href="javascript:void(0);" role="button">
                    <i class="fas fa-expand-arrows-alt"></i>
                </a>
            </li>
        </ul>
    </nav>

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="{{ route('admin.home') }}" class="brand-link">
            <img src="{{ asset('images/AdminLogo.png') }}" class="brand-image img-circle elevation-3" style="opacity: .8">
            <span class="brand-text font-weight-light">@lang('admin_panel_name')</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">

            @include('backend.layouts.menu')

        </div>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        @include('backend.layouts.breadcrumb')

        <button class="open-menu"><img src="/images/menu.svg" alt="icon"></button>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                @include('backend.layouts.notification')
                @yield('content')
            </div><!-- /.container-fluid -->
        </section>
    </div>

    @include('backend.layouts.footer')

    @yield('end_load')
</div>
<!-- ./wrapper -->
    @include('backend.layouts.scripts')
</body>
</html>

resources/views/backend/layouts/auth.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin Panel</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('assets/backend/css/fontawesome/css/all.min.css') }}">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="{{ asset('assets/backend/css/icheck-bootstrap.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('assets/backend/css/adminlte.min.css') }}">
</head>
<body class="hold-transition login-page">

    @yield('content')


    <!-- jQuery -->
    <script src="{{ asset('assets/backend/js/jquery.min.js') }}"></script>
    <!-- Bootstrap 4 -->
    <script src="{{ asset('assets/backend/js/bootstrap.bundle.min.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset('assets/backend/js/adminlte.min.js') }}"></script>
</body>
</html>

resources/views/backend/layouts/breadcrumb.blade.php
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">@yield('title')</h1>
            </div><!-- /.col -->
            @if(!Route::is('admin.home'))
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">{{ trans('admin.home_page') }}</a></li>
                        @hasSection('title')
                            <li class="breadcrumb-item active">@yield('title')</li>
                        @endif
                    </ol>
                </div><!-- /.col -->
            @endif
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

resources/views/backend/layouts/footer.blade.php
<!-- Sidebar Menu -->
<footer class="main-footer">
    <strong>Copyright &copy; 2021.</strong>
    All rights reserved.
</footer>
<!-- /.sidebar-menu -->

resources/views/backend/layouts/menu.blade.php
@php
    /** @var \App\Models\User $user */
    $user = auth()->user();
@endphp
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column mb-5" data-widget="treeview" role="menu" data-accordion="false">
        @canany(['posts/*', 'posts/index'])
            <li class="nav-header">@lang('admin.posts')</li>
            @canany(['posts/*', 'posts/pending'])
                <li class="nav-item">
                    <a href="{{ route('admin.posts.list', ['type' => \App\Enum\PostActionType::PENDING]) }}" class="nav-link">
                        <i class="nav-icon fas fa-list"></i>
                        <p>
                            @lang('admin.menu.posts-pending')
                        </p>
                    </a>
                </li>
            @endcanany
            @canany(['posts/*', 'posts/published'])
                <li class="nav-item">
                    <a href="{{ route('admin.posts.list', ['type' => \App\Enum\PostActionType::PUBLISHED]) }}" class="nav-link">
                        <i class="nav-icon fas fa-list"></i>
                        <p>
                            @lang('admin.menu.posts-published')
                        </p>
                    </a>
                </li>
            @endcanany
            @canany(['posts/*', 'posts/deleted'])
                <li class="nav-item">
                    <a href="{{ route('admin.posts.list', ['type' => \App\Enum\PostActionType::DELETED]) }}" class="nav-link">
                        <i class="nav-icon fas fa-list"></i>
                        <p>
                            @lang('admin.menu.posts-deleted')
                        </p>
                    </a>
                </li>
            @endcanany
        @endif

        <li class="divider"></li>

        @canany(['tags/*', 'tags/index'])
            <li class="nav-item">
                <a href="{{ route('admin.tags.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-tags"></i>
                    <p>
                        @lang('admin.menu.tags')
                    </p>
                </a>
            </li>
        @endcanany

        @canany(['categories/*', 'categories/index'])
            <li class="nav-item">
                <a href="{{ route('admin.categories.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-align-left"></i>
                    <p>
                        @lang('admin.menu.categories')
                    </p>
                </a>
            </li>
        @endcanany

        @canany(['pages/*', 'pages/index'])
            <li class="nav-item">
                <a href="{{ route('admin.pages.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-book"></i>
                    <p>
                        @lang('admin.menu.pages')
                    </p>
                </a>
            </li>
        @endcanany

        @canany(['users/*', 'users/index'])
            <li class="nav-item">
                <a href="{{ route('admin.users.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-user"></i>
                    <p>
                        @lang('admin.menu.users')
                    </p>
                </a>
            </li>
        @endcanany

        <li class="divider"></li>

        @canany(['main-info/*'])
            <li class="nav-item">
                <a href="{{ route('admin.main-info') }}" class="nav-link">
                    <i class="nav-icon fas fa-info-circle"></i>
                    <p>
                        @lang('admin.menu.main-info')
                    </p>
                </a>
            </li>
        @endcanany
        @canany(['configs/*'])
            <li class="nav-item">
                <a href="{{ route('admin.configs.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-cogs"></i>
                    <p>
                        @lang('admin.menu.configs')
                    </p>
                </a>
            </li>
        @endcanany
        @canany(['translations/*'])
            <li class="nav-item">
                <a href="{{ route('admin.translates.view') }}" class="nav-link">
                    <i class="nav-icon fas fa-language"></i>
                    <p>
                        @lang('admin.menu.translations')
                    </p>
                </a>
            </li>
        @endcanany

        @canany(['settings/*'])
            <li class="nav-item">
                    <a href="javascript:void(0);" class="nav-link">
                        <i class="nav-icon fas fa-cogs"></i>
                        <p>
                            @lang('admin.menu.settings')
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('admin.settings.index') }}" class="nav-link">
                                <p>
                                    <i class="nav-icon">-</i>
                                    @lang('admin.menu.general_settings')
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin.logs.index') }}" class="nav-link">
                                <p>
                                    <i class="nav-icon">-</i>
                                    @lang('admin.menu.logs')
                                </p>
                            </a>
                        </li>
                    </ul>
                </li>
        @endcan
    </ul>
</nav>

resources/views/backend/layouts/notification.blade.php
@if(session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

@if(session('error'))
    <div class="alert alert-danger">
        {{ session('error') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

resources/views/backend/layouts/styles.blade.php
<link rel="stylesheet" href="{{ asset('assets/backend/css/fontawesome/css/all.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/backend/css/daterangepicker.css') }}">
<link rel="stylesheet" href="{{ asset('assets/backend/css/fileinput.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/backend/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/backend/css/tempusdominus-bootstrap-4.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/backend/css/bootstrap-datepicker.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/backend/css/adminlte.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/backend/css/OverlayScrollbars.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/backend/css/dropzone.css') }}">
<link rel="stylesheet" href="{{ asset('assets/backend/css/bootstrap-icons.min.css') }}">
<link rel="stylesheet" href="/assets/backend/css/admin.css?v=1.1.6">

@yield('admin_styles')