routes/admin.php
<?php

use App\Http\Controllers\TinymceController;
use App\Http\Controllers\Backend\{Auth\LoginController,
    CategoryController,
    ConfigController,
    MainInfoController,
    PageController,
    PhotoController,
    PostController,
    Settings\LogController,
    Settings\SettingController,
    SiteController,
    TagController,
    TranslateController,
    UserController};
use App\Http\Controllers\CkeditorController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth', 'preventBackHistory'])->group(function () {
    Route::get('/', [SiteController::class, 'index'])->name('home');
    Route::get('/change-locale/{lang}', [SiteController::class, 'changeLocale'])->name('change-locale');

    Route::middleware('can:settings/*')->group(function () {
        Route::resource('settings', SettingController::class)->except(['show']);
        Route::resource('logs', LogController::class)->only(['index', 'show']);
        Route::put('settings/chosen-tags/update/{id}', [SettingController::class, 'updateChosenTags'])->name('settings.chosen-tags.update');
    });

    Route::middleware('can:categories/*')->group(function () {
        Route::resource('categories', CategoryController::class)->except(['show']);
        Route::get('categories/move/{id}/{type}', [CategoryController::class, 'move'])
            ->where('type', 'up|down')
            ->where('id', '[0-9]+')
            ->name('categories.move');
        Route::get('categories/translate-list', [CategoryController::class, 'translateList'])
            ->middleware('crossAjax')
            ->name('categories.translate-list');
        Route::get('categories/create-translate', [CategoryController::class, 'create'])
            ->middleware('crossAjax')
            ->name('categories.createTranslate');
    });

    Route::middleware('can:tags/*')->group(function () {
        Route::get('tags/merge', [TagController::class, 'merge'])
            ->name('tags.merge');
        Route::resource('tags', TagController::class);
    });

    Route::get('post/restore/{id}', [PostController::class, 'restore'])
        ->middleware('can_any:post/*|post/restore')
        ->name('post.restore');
    Route::get('post/publish/{id}', [PostController::class, 'publish'])
        ->middleware('can_any:post/*|post/publish')
        ->name('post.publish');
    Route::get('post/reject/{id}', [PostController::class, 'reject'])
        ->middleware('can_any:post/*|post/reject')
        ->name('post.reject');

    Route::get('post/delete-reason', [PostController::class, 'deleteReason'])
        ->middleware('can_any:*/delete|posts/*')
        ->name('post.deleteReason');

    Route::resource('post', PostController::class);
    Route::put('post/update-counts/{id}', [PostController::class, 'updateCounts'])
        ->middleware('can_any:post/*|posts/*')
        ->name('post.update-counts');
    Route::get('post/cancel-form/{id}', [PostController::class, 'cancelForm'])
        ->name('post.cancel-form');

    Route::get('posts/tag-list', [PostController::class, 'tagList'])
        ->middleware(['can_any:posts/*|posts/create|posts/edit', 'crossAjax'])
        ->name('posts.tag-list');

    Route::get('posts/translate-list', [PostController::class, 'translateList'])
        ->middleware('can_any:posts/*|posts/create|posts/edit')
        ->name('posts.translate-list');

    Route::get('posts/reference-list', [PostController::class, 'referenceList'])
        ->middleware(['can_any:posts/*|posts/create|posts/edit', 'crossAjax'])
        ->name('posts.reference-list');

    Route::get('posts/create-translate', [PostController::class, 'create'])
        ->middleware(['can_any:posts/*|posts/create', 'crossAjax'])
        ->name('posts.createTranslate');

    Route::get('posts/{type}', [PostController::class, 'index'])
        ->middleware('post_authorize')
        ->name('posts.list');

    Route::middleware('can:pages/*')->group(function () {
        Route::resource('pages', PageController::class)->except(['show']);
        Route::post('pages/image-delete/{id}', [PageController::class, 'imageDelete'])
            ->where('id', '[0-9]+')
            ->name('pages.image-delete');
        Route::get('pages/move/{id}/{type}', [PageController::class, 'move'])
            ->where('type', 'up|down')
            ->where('id', '[0-9]+')
            ->name('pages.move');
    });

    Route::middleware('can:users/*')->group(function () {
        Route::resource('users', UserController::class);
        Route::post('users/delete-thumb/{id}', [UserController::class, 'deleteThumb'])
            ->name('users.delete-image');
    });

    Route::middleware('can:main-info/*')->group(function () {
        Route::post('main-info/delete-logo/{id}/{lang}', [MainInfoController::class, 'deleteLogo'])
            ->name('main-info.delete-logo');
        Route::post('main-info/delete-favicon/{id}/{lang}', [MainInfoController::class, 'deleteFavicon'])
            ->name('main-info.delete-favicon');
        Route::get('main-info', [MainInfoController::class, 'index'])->name('main-info');
        Route::put('main-info', [MainInfoController::class, 'update'])->name('main-info.update');
    });

    Route::resource('configs', ConfigController::class)
        ->middleware('can:configs/*')
        ->except(['show']);

    Route::resource('translations', TranslateController::class)
        ->middleware('can:translations/*')
        ->except(['show']);

    Route::resource('translates', TranslateController::class)
        ->middleware('can:translations/*')
        ->except(['show']);

    Route::get('translates/view', [TranslateController::class, 'view'])
        ->middleware('can:translations/*')
        ->name('translates.view');

    Route::post('ckeditor/image_upload', [CkeditorController::class, 'upload'])->name('ckeupload');
    Route::post('tinymce/addWidget', [TinymceController::class, 'addWidget'])
        ->name('tinymce.addWidget');

    Route::prefix('photos')->middleware('can:photos/*')->name('photos.')->group(function () {
        Route::get('index', [PhotoController::class, 'index'])->name('index');
        Route::get('folder', [PhotoController::class, 'folderIndex'])->name('folder');
        Route::get('trash', [PhotoController::class, 'trashIndex'])->name('trash');
        Route::get('restore', [PhotoController::class, 'restore'])->name('restore');
        Route::post('create', [PhotoController::class, 'create'])->name('create');
        Route::get('update', [PhotoController::class, 'update'])->name('update');
        Route::post('update', [PhotoController::class, 'update'])->name('update.submit');
        Route::post('size', [PhotoController::class, 'size'])->name('size.submit');
        Route::get('create-folder', [PhotoController::class, 'folderCreate'])->name('create-folder');
        Route::get('delete-folder', [PhotoController::class, 'folderDelete'])->name('delete-folder');
        Route::get('update-folder', [PhotoController::class, 'folderUpdate'])->name('update-folder');
        Route::post('update-folder', [PhotoController::class, 'folderUpdate'])->name('update-folder.submit');
        Route::post('create-folder', [PhotoController::class, 'folderCreate'])->name('create-folder.submit');
        Route::post('delete', [PhotoController::class, 'delete'])->name('delete');
        Route::post('soft-delete', [PhotoController::class, 'softDelete'])->name('softDelete');
        Route::post('crop', [PhotoController::class, 'crop'])->name('crop');
        Route::get('sort', [PhotoController::class, 'sort'])->name('sort');
        Route::post('render-gallery', [PhotoController::class, 'renderGallery'])->name('render-gallery');
        Route::post('get-size', [PhotoController::class, 'getSize'])->name('get-size');
    });
});

Route::middleware(['preventBackHistory'])->group(function () {
    Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('login', [LoginController::class, 'login'])->name('login.login');
    Route::get('logout', [LoginController::class, 'logout'])->name('logout');
});

routes/web.php
<?php

//

app/Models/Config/ConfigTranslation.php
<?php
declare(strict_types=1);

namespace App\Models\Config;

use Illuminate\Database\Eloquent\Model;

class ConfigTranslation extends Model
{
    public $fillable   = ['value'];
    public $timestamps = false;
}

app/Http/Controllers/Backend/BaseController.php
<?php

namespace App\Http\Controllers\Backend;

class BaseController
{
}

app/Http/Controllers/Backend/CategoryController.php
<?php
declare(strict_types=1);

namespace App\Http\Controllers\Backend;

use DB;
use Exception;
use RuntimeException;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Repositories\CategoryRepository;
use App\Http\Controllers\Controller;
use Illuminate\Http\RedirectResponse;
use App\Services\manager\CategoryService;
use Itstructure\GridView\DataProviders\EloquentDataProvider;
use App\Http\Requests\Category\{CategoryCreateRequest, CategoryUpdateRequest};

class CategoryController extends Controller
{

    public function __construct(
        private CategoryRepository $categoryRepository,
        private CategoryService $categoryService
    )
    {
    }

    public function index()
    {
        $lang = request()->input('filters.language');
        if ($lang) {
            session()->put('current-lang', $lang);
        }
        $lang  = (session()->get('current-lang') ?? $lang) ?? config('app.admin_content_locale');
        $query = Category::query()
            ->where('language', $lang)
            ->defaultOrder();

        $dataProvider = new EloquentDataProvider($query);

        return view('backend.categories.index', [
            'dataProvider' => $dataProvider
        ]);
    }

    public function create()
    {
        if ($lang = request()->get('lang')) {
            if ($id = request()->get('id')) {
                $category = Category::findOrFail($id);
                if ($translatedCategory = Category::where('group_id', $category->group_id)->where('language', $lang)->first()) {
                    return redirect()->route('admin.categories.edit', $translatedCategory);
                }
            }

            return view('backend.categories.create', [
                'lang'                 => $lang,
                'translatedCategoryId' => request('id'),
            ]);
        }

        return redirect()->route('admin.categories.index');
    }

    public function store(CategoryCreateRequest $request)
    {
        try {
            $this->categoryService->create($request);
            return redirect()->route('admin.categories.index')
                ->with('success', trans('form.success.save'));
        } catch (Exception $e) {
            return redirect()->route('admin.categories.index')
                ->with('error', trans('form.error.save'));
        }
    }

    public function show(Category $category)
    {
        return view('backend.categories.view', [
            'category' => $category
        ]);
    }

    public function edit(Category $category)
    {
        return view('backend.categories.update', [
            'category'             => $category,
            'translatedCategories' => $this->categoryRepository->translatedCats($category->group_id, $category->id),
        ]);
    }

    public function update(CategoryUpdateRequest $request, Category $category)
    {
        try {
            $this->categoryService->update($request, $category);
            return redirect()->route('admin.categories.index')
                ->with('success', trans('form.success.save'));
        } catch (Exception $e) {
            return redirect()->route('admin.categories.index')
                ->with('error', trans('form.error.save'));
        }
    }

    public function destroy(Category $category): RedirectResponse
    {
        try {
            $this->categoryService->remove($category);
            return redirect()->route('admin.categories.index')
                ->with('success', trans('form.success.delete'));
        } catch (RuntimeException $e) {
            return redirect()->route('admin.categories.index')
                ->with('error', trans('form.error.delete'));
        }
    }

    public function move(int $id, string $type): RedirectResponse
    {
        try {
            /** @var Category $category */
            $category = Category::findOrFail($id);
            ($type == 'up') ? $category->up() : $category->down();
        } catch (Exception $e) {
            \Log::debug($e);
        }

        return redirect()->route('admin.categories.index', ['page' => \request('page'), '_debug_' => true]);
    }

    public function translateList(Request $request)
    {
        $posts = $this->categoryRepository->getByQuery($request->q, $request->lang, $request->chosen)->toArray();

        return response()->json(['results' => array_values($posts)]);
    }

}

app/Http/Controllers/Backend/CityController.php
<?php
declare(strict_types=1);

namespace App\Http\Controllers\Backend;

use App\Helpers\NodeHelper;
use App\Http\Controllers\Controller;
use App\Http\Requests\City\CityCreateRequest;
use App\Http\Requests\City\CityUpdateRequest;
use App\Models\City\City;
use App\Services\manager\CityService;
use Exception;
use Illuminate\Http\RedirectResponse;
use Itstructure\GridView\DataProviders\EloquentDataProvider;
use RuntimeException;

class CityController extends Controller
{
    private $cityService;

    public function __construct(CityService $cityService)
    {
        $this->cityService = $cityService;
    }

    public function index()
    {
        $query = City::query()->withDepth()->defaultOrder();
        $dataProvider = new EloquentDataProvider($query);

        return view('backend.cities.index', [
            'dataProvider' => $dataProvider
        ]);
    }

    public function create()
    {
        $parents = (new NodeHelper(City::class))->map();

        return view('backend.cities.create', compact('parents'));
    }

    public function store(CityCreateRequest $request)
    {
        try {
            $this->cityService->create($request);
            return redirect()->route('admin.cities.index')
                ->with('success', trans('form.success.save'));
        } catch (Exception $e) {
            return redirect()->route('admin.cities.index')
                ->with('error', trans('form.error.save'));
        }
    }

    public function show(City $category)
    {
        return view('backend.cities.view', [
            'category' => $category
        ]);
    }

    public function edit(City $city)
    {
        $parents = (new NodeHelper($city))->map();

        return view('backend.cities.update', compact('city', 'parents'));
    }

    public function update(CityUpdateRequest $request, City $city)
    {
        try {
            $this->cityService->update($request, $city);
            return redirect()->route('admin.cities.index')
                ->with('success', trans('form.success.save'));
        } catch (Exception $e) {
            return redirect()->route('admin.cities.index')
                ->with('error', trans('form.error.save'));
        }
    }

    public function destroy(City $city): RedirectResponse
    {
        try {
            $this->cityService->remove($city);
            return redirect()->route('admin.cities.index');
        } catch (RuntimeException $e) {
            return redirect()->route('admin.cities.index')->with('error', $e->getMessage());
        }
    }

    public function move(int $id, string $type): RedirectResponse
    {
        $category = City::findOrFail($id);
        ($type == 'up') ? $category->up() : $category->down();

        return redirect()->back();
    }
}

app/Http/Controllers/Backend/ConfigController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Config\ConfigRequest;
use App\Models\Config\Config;
use App\Services\manager\ConfigService;
use Itstructure\GridView\DataProviders\EloquentDataProvider;

class ConfigController extends Controller
{
    private $configService;

    public function __construct(ConfigService $configService)
    {
        $this->configService = $configService;
    }

    public function index()
    {
        $dataProvider = new EloquentDataProvider(Config::query()->orderByDesc('id'));
        return view('backend.configs.index', [
            'dataProvider' => $dataProvider
        ]);
    }

    public function create()
    {
        return view('backend.configs.create');
    }

    public function store(ConfigRequest $request)
    {
        try {
            $this->configService->create($request);
            return redirect()->route('admin.configs.index')
                ->with('success', trans('form.success.save'));
        }
        catch (\Exception $e) {
            return redirect()->route('admin.configs.index')
                ->with('error', trans('form.success.error'));
        }
    }

    public function edit(Config $config)
    {
        return view('backend.configs.update', [
            'config' => $config
        ]);
    }

    public function update(ConfigRequest $request, Config $config)
    {
        try {
            $this->configService->update($config, $request);
            return redirect()->route('admin.configs.index')
                ->with('success', trans('form.success.save'));
        } catch (\Exception $e) {
            return redirect()->route('admin.configs.index')
                ->with('error', trans('form.success.error'));
        }
    }

    public function destroy(Config $config)
    {
        try {
            $this->configService->remove($config);
            return redirect()->route('admin.configs.index');
        } catch (\Exception $e) {
            return redirect()->route('admin.configs.index');
        }
    }
}

resources/views/backend/configs/create.blade.php
@extends('backend.layouts.app')

@section('title', trans('admin.new_config'))

@section('content')
    <div class="mt-3">
        <div>
            <form action="{{ route('admin.configs.store') }}" method="POST">
                @csrf
                <div class="row">
                    <div class="col-md-12">
                        <div class="card card-primary card-outline card-tabs">
                            <div class="card-header p-0 pt-1 border-bottom-0">
                                <ul class="nav nav-tabs" id="custom-tabs-three-tab" role="tablist">
                                    @foreach(LaravelLocalization::getSupportedLanguagesKeys() as $key => $lang)
                                        <li class="nav-item">
                                            <a class="nav-link @if($key == 0) active @endif" id="tab-{{ $lang }}" data-toggle="pill" href="#tablink-{{ $lang }}" role="tab" aria-controls="tablink-{{ $lang }}" aria-selected="true">{{ strtoupper($lang) }}</a>
                                        </li>
                                    @endforeach
                                </ul>
                            </div>

                            <div class="card-body">
                                <div class="form-group">
                                    <label for="param">@lang('admin.config_param')</label>
                                    <input type="text" id="param" class="form-control @error('param') is-invalid @enderror" name="param" value="{{ old('param') }}">
                                    @error('param')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="tab-content" id="custom-tabs-three-tabContent">
                                    @foreach(LaravelLocalization::getSupportedLanguagesKeys() as $key => $lang)
                                        <div class="tab-pane fade @if($key == 0) show active @endif" id="tablink-{{ $lang }}" role="tabpanel" aria-labelledby="tab-{{ $lang }}">
                                            <div class="form-group">
                                                <label for="value-{{ $lang }}">@lang('admin.config_value')</label>
                                                <textarea name="value[{{ $lang }}]" id="value-{{ $lang }}" rows="4" class="form-control @error('value.' . $lang) is-invalid @enderror">{{ old('value.' . $lang) }}</textarea>
                                                @error('value.'  . $lang)
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                @enderror
                                            </div>
                                        </div>
                                    @endforeach
                                </div>

                                <div class="form-group">
                                    <label for="default">@lang('admin.config_default')</label>
                                    <textarea name="default" id="default" rows="4" class="form-control @error('default') is-invalid @enderror">{{ old('default') }}</textarea>

                                    @error('default')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="label">@lang('admin.config_label')</label>
                                    <input type="text" id="label" class="form-control @error('label') is-invalid @enderror" name="label" value="{{ old('label') }}">
                                    @error('label')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="type">@lang('admin.config_type')</label>
                                    <input type="text" id="type" class="form-control @error('type') is-invalid @enderror" name="type" value="{{ old('type') }}">
                                    @error('type')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <input type="submit" value="@lang('admin.save')" class="btn btn-success float-right">
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/backend/configs/index.blade.php
@extends('backend.layouts.app')

@section('title', trans('admin.configs'))

@section('content')
    <div class="mt-3">
        {!!
            grid([
                'dataProvider' => $dataProvider,
                'hideCreateButton' => true,
                'columnFields' => [
                [
                    'label' => trans('admin.config_param'),
                    'attribute' => 'param'
                ],
                [
                    'label' => trans('admin.config_value'),
                    'attribute' => 'value',
                    'value' => function ($data) {
                        return $data->translate(config('app.admin_content_locale'))->value;
                    }
                ],
                [
                    'label' => trans('admin.config_default'),
                    'attribute' => 'default'
                ],
                [
                    'label' => trans('admin.config_label'),
                    'attribute' => 'label'
                ],
                [
                    'label' => trans('admin.config_type'),
                    'attribute' => 'type'
                ],
                [
                    'label' => '',
                    'class' => \App\Components\Grid\ActionColumn::class,
                    'actionTypes' => [
                        'edit'
                    ]
                ]
            ]
            ])
        !!}
    </div>
@endsection

resources/views/backend/configs/update.blade.php
@extends('backend.layouts.app')

@section('title', $config->param)

@section('content')
    <div class="mt-3">
        <div>
            <form action="{{ route('admin.configs.update', $config->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="col-md-12">
                        <div class="card card-primary card-outline card-tabs">
                            <div class="card-header p-0 pt-1 border-bottom-0">
                                <ul class="nav nav-tabs" id="custom-tabs-three-tab" role="tablist">
                                    @foreach(LaravelLocalization::getSupportedLanguagesKeys() as $key => $lang)
                                        <li class="nav-item">
                                            <a class="nav-link @if($key == 0) active @endif" id="tab-{{ $lang }}" data-toggle="pill" href="#tablink-{{ $lang }}" role="tab" aria-controls="tablink-{{ $lang }}" aria-selected="true">{{ strtoupper($lang) }}</a>
                                        </li>
                                    @endforeach
                                </ul>
                            </div>

                            <div class="card-body">
                                <div class="form-group">
                                    <label for="param">@lang('admin.config_param')</label>
                                    <input type="text" id="param" class="form-control @error('param') is-invalid @enderror" name="param" value="{{ $config->param }}">
                                    @error('param')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="tab-content" id="custom-tabs-three-tabContent">
                                    @foreach(LaravelLocalization::getSupportedLanguagesKeys() as $key => $lang)
                                        <div class="tab-pane fade @if($key == 0) show active @endif" id="tablink-{{ $lang }}" role="tabpanel" aria-labelledby="tab-{{ $lang }}">
                                            <div class="form-group">
                                                <label for="value-{{ $lang }}">@lang('admin.config_value')</label>
                                                <textarea name="value[{{ $lang }}]" id="value-{{ $lang }}" rows="4" class="form-control @error('value.' . $lang) is-invalid @enderror">{{ $config->translate($lang)?->value }}</textarea>
                                                @error('value.' . $lang)
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                @enderror
                                            </div>
                                        </div>
                                    @endforeach
                                </div>

                                <div class="form-group">
                                    <label for="default">@lang('admin.config_default')</label>
                                    <textarea name="default" id="default" rows="4" class="form-control @error('default') is-invalid @enderror">{{ $config->default }}</textarea>

                                    @error('default')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="label">@lang('admin.config_label')</label>
                                    <input type="text" id="label" class="form-control @error('label') is-invalid @enderror" name="label" value="{{ $config->label }}">
                                    @error('label')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="type">@lang('admin.config_type')</label>
                                    <input type="text" id="type" class="form-control @error('type') is-invalid @enderror" name="type" value="{{ $config->type }}">
                                    @error('type')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <input type="submit" value="@lang('admin.save')" class="btn btn-success float-right">
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection